clojure.json

As documented here: https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate

Add checkver and autoupdate support

---

clojure.json
clojure.sh

Remove shim

---

clojure.json

This version includes a fix for Windows in multiple alias option handling.

Update to 489

---

joker.json
joker.sh

Include only 64bit architecture

Refactoring: Joker manifest

---

clojure.json

Update to 1.10.1.492

---

clj-kondo.json
deps.clj.json
scripts/clj-kondo.sh
scripts/deps.clj.sh

Add suggestion to extras/vcredist2010

---

babashka.json

"Keep it clean" build with breaking changes

Update babashka, v0.0.90

---

babashka.json

Update babashka, v0.0.92, pods

---

babashka.json

Update babashka, v0.0.93

---

babashka.json
clj-kondo.json

- clj-kondo v2020.05.09
- babashka v0.0.94

Updates: babashka, clj-kondo

---

babashka.json
bootleg.json
clj-kondo.json
deps.clj.json
jet.json
scripts/babashka.sh
scripts/bootleg.sh
scripts/clj-kondo.sh
scripts/deps.clj.sh
scripts/jet.sh

- suggest is for optional deps
- depends is a required runtime dependency

Use depends instead of suggest

---

clojure.json

clojure: Update to v1.10.1.672

---

clj-kondo.json

[Changelog](https://github.com/borkdude/clj-kondo/blob/master/CHANGELOG.md#v20200909)

clj-kondo: Update to v2020.09.09

---

babashka.json

[Changelog](https://github.com/borkdude/babashka/blob/v0.2.1/CHANGELOG.md)

babashka: Update to v0.2.1

---

clojure.json

clojure: Update to stable release v1.10.1.697

---

deps.clj.json

deps.clj: Fix broken artifact v0.0.10

---

babashka.json

[Changelog](https://github.com/borkdude/babashka/blob/master/CHANGELOG.md#v022-2020-09-30)

babashka: Update to v0.2.2

---

clojure.json

clojure: Update to v1.10.1.716

---

clojure.json

Fix clj -X:deps tree adding tools.deps.alpha to tree
Fix clj -X:deps mvn-pom adding tools.deps.alpha to pom deps
Fix clj -X:deps git-resolve-tags not working
Fix clj -X:deps mvn-install on jar to also install embedded pom
Fix clj -Spom not paying attention to deps changes in -A (regression)

clojure: Update to v1.10.1.727

---

README.md
puget.json

puget: Add version 0.0.1-snapshot

---

README.md
grasp.json

grasp: Add version 0.0.1-snapshot

---

clj-kondo.json

[Changelog to v2020.11.07](https://github.com/borkdude/clj-kondo/blob/master/CHANGELOG.md#v20201107)

clj-kondo: Update to v2020.11.07

---

README.md
pgmig.json
scripts/pgmig.sh

[Changelog v0.5.0](https://github.com/leafclick/pgmig/blob/master/CHANGELOG.md#050---2020-11-09)

pgmig: Add version 0.5.0

---

babashka.json

[Changelog for v0.2.4](https://github.com/borkdude/babashka/blob/master/CHANGELOG.md#v024)

babashka: Update to version 0.2.4

---

clj-kondo.json

[Changelog](https://github.com/borkdude/clj-kondo/blob/master/CHANGELOG.md#v20201212)

clj-kondo: Update to version 2020.12.12

---

babashka.json

[Changelog for v0.2.5](https://github.com/borkdude/babashka/blob/master/CHANGELOG.md#v025)

babashka: Update to version 0.2.5

---

clojure.json

https://clojure.org/releases/tools#v1.10.1.763

clojure: Update to version 1.10.1.763

---

babashka.json

[Changelog v0.2.6](https://github.com/borkdude/babashka/blob/master/CHANGELOG.md#v026)

babashka: Update to version 0.2.6

---

README.md
puget.json
scripts/puget.sh

Going from development preview to release

puget: Update to release version 0.0.1

---

README.md
carve.json
scripts/carve.sh

carve: Add version 0.0.1

---

puget.json

From changelog
- Handle multiple EDN forms on stdin

puget: Update to version 0.0.2

---

scripts/babashka.sh
scripts/bb-web.sh
scripts/bootleg.sh
scripts/carve.sh
scripts/clj-kondo.sh
scripts/clojure.sh
scripts/deps.clj.sh
scripts/jet.sh
scripts/joker.sh
scripts/pgmig.sh
scripts/puget.sh

Make sure scripts generate the proper structure of manifests

chore: Improve scripts

---

scripts/joker.sh

There is a mistake in joker manifest which prevents checkver to work.

chore: Fix joker script

---

README.md
bucket/clojure-lsp.json

clojure-lsp: Add version 2021.02.07-03.04.31

---

README.md
bucket/lmgrep.json

Add `lmgrep` to the list of programs in the scoop bucket.

lmgrep: Add version 2021.04.26

---

bucket/clojure.json

- Change checkver url and regular expression
- Use official tools release page where version is listed

clojure: Update checkver

---

README.md
bucket/cq.json

Clojure Command-line Data Processor for JSON, YAML, EDN, XML and more

cq: Add version 2022.01.26-15.35.00

---

README.md
bucket/grasp.json

grasp: Add version 0.0.3

---

README.md
bucket/bb-http-server.json

Standalone http-server powered by Babashka
```
$ scoop install bb-http-server
$ cd dir-to-serve
$ http-server
Serving assets at http://localhost:8090
```

bb-http-server: Add version 0.1.4

---

.appveyor.yml
.github/workflows/issue.yml
.github/workflows/issue_comment.yml
.github/workflows/pull_request.yml
.github/workflows/schedule.yml
.vscode/extensions.json
.vscode/json.code-snippets
.vscode/settings.json
.vscode/tasks.json
Bucket.Tests.ps1

shovel-org bucket migration

---

bucket/clojure-lsp.json

clojure-lsp: Adhere to manifest schema

---

README.md
bucket/eql-cli.json

eql-cli: Add version 0.0.2

---

bucket/eql-cli.json
bucket/neil.json

Babashka scripts are usually concated together and prod scripts are one file only. The rest is not needed unless you're a dev.

chore: Optimize deployments

---

README.md
bucket/bbin.json

`bbin` is a standalone babashka script or project installer. 
Requested here: https://github.com/babashka/bbin/issues/16

bbin: Add version 0.0.10

---

bucket/bbin.json

Path added to PATH environment variable should be `%USERPROFILE%\.bbin\bin`

bbin: Fix path to scripts

---

bucket/bbin.json

Add notes about PATH variable change and suggest to restart the terminal application

bbin: Add notes
