- clojure.json
- scripts/clojure.sh
- clj and clojure are Powershell aliases and as such cannot be used directly from cmd.exe
- this experiments adds cmd-clj and cmd-clojure shims allow to run tooling from cmd.exe
- powershell is still required to be installed on the box
> Add cmd-clojure and cmd-clj shims

- babashka.json
- scripts/babashka.sh
- update to the new dependency on vcredist2015
- built with GraalVM v20.1.0
- pods are working
> Update babashka, v0.0.98, dep: vcredist2015

- bootleg.json
From the release notes:
- add babashka pod support
- YAML upgrade to SnakeYAML 2.0
- Fix Build failed when trying build with graalvm-ce-java11-19.3.0
- Fix the ns/require code from spire in bootleg?
- Fix Running from file in same directory requires leading ./
- Fix Generating XML preserving the tag name case
- Fix reflection error preventing XML roundtrip
> Update bootleg, v0.1.8

- clojure.json
Reference: https://insideclojure.org/2020/07/28/clj-exec/
> clojure: Update to v1.10.1.600

- deps.clj.json
- Support proxy env variables while downloading tool jars
- Parity with clj 1.10.1.697
> deps.clj: Update to v0.0.10

- clojure.json
[Changelog v1.10.1.708](https://clojure.org/releases/tools#v1.10.1.708)
> clojure: Update to v1.10.1.708

- clojure.json
- Fix use of jdk profile activation in local deps with pom files
- Fix error handling for -X to avoid double throw
- Add error handling for -A used without an alias
- Use tools.deps.alpha 0.9.840
> clojure: Update to version 1.10.1.739

- clojure.json
- New, more informative tree format for clj -Stree / clj -X:deps tree
- Added options for use with clj -X:deps tree
- Use tools.deps.alpha 0.9.857
> clojure: Update to version 1.10.1.754

- bucket/clojure-lsp.json
Fix eventual missing dependency on vcredist2015 dynamic library
> clojure-lsp: Add depends on extras/vcredist2015

- bucket/datalevin.json
Datalevin is a simple durable Datalog database.
The rationale is to have a simple, fast and free Datalog query engine running on durable storage. It is our observation that many developers prefer the flavor of Datalog popularized by Datomic® over any flavor of SQL, once they get to use it. Perhaps it is because Datalog is more declarative and composable than SQL, e.g. the automatic implicit joins seem to be its killer feature.
> datalevin: Add version 0.4.25

- README.md
- bucket/pathom-viz.json
Pathom viz is a set of visualization tools to support the development and inspection of Graph API’s built with the Pathom library
> pathom-viz: Add version 2021.4.22

- bucket/babashka.json
Current version of Windows is bundled with the older version of `curl` tool which causes trouble on some occasions.
See https://github.com/babashka/babashka.curl/issues/36
As a result I added curl to suggest section of the manifest, so user have a change to grab the newer  version out of scoop main bucket.
Setting up PATH properly to take precedence over bundled curl may be still required though.
> babashka: Add curl to suggest section

- README.md
- bucket/neil.json
Babashka utility: A CLI to add common aliases and features to deps.edn-based projects
> neil: Add version 0.0.9

- README.md
Since [AdoptOpenJDK](https://adoptopenjdk.net) is end of life and recommends switching to [Adoptium](https://adoptium.net).
Let's do this, Temurin is the way to go.
> Switch to Temurin JDK in README

- bucket/neil.json
Previously this depends on neil.bat from neil repository. But this is how shim can be generated form the manifest.
> neil: Generate shim from manifest

- bucket/clojure.json
- Remove suggestion adopopenjdk, use temurin instead.
- Remove suggestion of jdk version 8.
> clojure: Change jdk suggestion

- README.md
- bucket/trenchman.json
Trenchman is a standalone nREPL/prepl client, which means that it can be used as an ordinary REPL without having to make it cooperate with an editor or any other development tool. Unlike ordinary Clojure REPLs, it starts up instantly as it just connects to a running nREPL/prepl server, eliminating the overhead of launching a JVM process and bootstrapping Clojure for every startup.
Features
- Fast startup
- Written in Go and runs on various platforms
- Support for nREPL and prepl
- Works as a language-agnostic nREPL client
> trenchman: Add version 0.4.0

- bucket/bbin.json
For some unknown reason, automation have rewritten path to a project from bbin to neil. Don't know what caused this.
> fix(bbin): Fix wrong path to project and artifact

- bucket/bbin.json
In `0.0.12`, we are changing the bin path from `~/.bbin/bin` to `~/.babashka/bbin/bin`:
https://github.com/babashka/bbin/blob/main/CHANGELOG.md#0012
> Update bbin bin path

- bucket/clj-msi.json
Installs Clojure using unofficial MSI installer in the making by @casselc
I did a quick round of testing and it works great as a source for a Clojure installation.
Few notes:
- This works in a way all the installations usint Scoop installer + MSI works, it uncompress the cabinet and setup all necessary stuff so it fits into Scoop structures and sets environment variables etc. 
- It relies on the fact that internal structure of the MSI package wont change drastically once established
- It's based on Pre-release, so don't depend on it too much yet. But we are getting there!
- I won't list this on the README as an installation option yet until it's out of pre-release
> clj-msi: Add version 1.11.1.1182

- bucket/clj-msi.json
- artifact location change
- use github defaults for checkver
> clj-msi: Update to version 1.11.1.1189 with manifest fixes

- README.md
- bucket/clj-deps.json
- bucket/clojure.json
This is a new way to install Clojure on Windows.
- It uses deps.exe from our own @borkdude
- creates three shims
- deps.exe
- clj.exe
- clojure.exe
> clj-deps: Add version 1.11.1.1200

- bucket/bbin.json
Check existence of `bbin/bin` directory and eventually create it.
> bbin: Create directory on install

- bucket/clj-deps.json
An attempt to avoid a bizzare behavior of Move-Item cmdlet
Closes #197
> fix: Simplify pre_install script to prevent error #197

- README.md
New executables are linked against vcredist2015 which are available via `extras` scoop.
Added instructions how to add extras before installing `clj-deps`
Closes #199
> README: Add instructions to add extras bucket

- bucket/clj-msi.json
- bucket/clojure.json
I consider `clojure` and `clj-msi` deprecated manifests. I updated description so it's more obvious to users.
Users should use `clj-deps`.
> Update descriptions of deprecated manifests

- bucket/babashka.json
The new version of Babashka has been built using the newer Visual Studio 2019 toolset
Recommendation is to link against to at least a version associated with this toolset.
https://learn.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-170
> babashka: Update version of vcredist package dependency

- bucket/clj-deps.json
- bucket/deps.clj.json
It turned out that versioning of deps.clj matches upstream Clojure CLI versioning and eventually add suffixes like -4.
This however is not compatible with a default checker code in Scoop.
I decided to use similar technique that I use for clojure-lsp manifest where url, regex and replace sections of checker are used to form a version that can be used to check and also download artifacts.
> deps.clj: Update checkver regexp to accomodate versioning scheme

- bucket/clj-deps.json
Manual bump for clj-deps needed.
> clj-deps: Stuck on version, manual version bump

- README.md
- bucket/babashka.json
- bucket/bb-web.json
- bucket/bibcal.json
- bucket/bootleg.json
- bucket/carve.json
- bucket/clj-deps.json
- bucket/clj-kondo.json
- bucket/clojure-lsp.json
- bucket/cq.json
- bucket/deps.clj.json
- bucket/grasp.json
- bucket/jet.json
- bucket/lmgrep.json
- bucket/pgmig.json
- bucket/puget.json
- bucket/shh.json
Microsoft did some changes in the way Visual Studio redistributable runtimes are available.
This was reflected in some important scoop formulas that we use as dependencies here in the bucket.
The changes are following: 
1. All the vcredist libraries including version 2013 and lower are newly available via `extras/vcredist` 
2. All the vcredist libraries including version 2015 and higher are newly available via `extras/vcredist2022`
It means that all scoop manifest needs to be updated to reference to the second case except the single case (bootlet) where we stil have a dependency on the former.
These installation steps need to be taken to recover form the change:
```
scoop uninstall vcredist2005 vcredist2008 vcredist2010 vcredist2012 vcredist2013 vcredist
scoop update
scoop install …
```
> vcredist: Fix all references to vcredist2015 and vcredist2010

- bucket/clj-deps.json
Change the location of the downloaded artifacts to release tags of [brew-install](https://github.com/clojure/brew-install) repository.
Closes #207
> clj-deps: Update to version 1.11.1.1403

- bucket/clojure.json
This only updates release download location to Github releases
Relates to #207
> clojure: Update release location

- bucket/bbin.json
bbin deside to follow XDG directory structure. This requires a slight change in the script.
One big downside is now that uninstaller section removes the path for anyone else. Let's see if that causes any trouble.
> change path to follow XDG standard

- bucket/clj-kondo.json
> [FIX] (clj-kondo): releases now hosted under organization clj-kondo
